// gen-images.js — Generate Wikipedia image mappings for all units
const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');
const aircraft = JSON.parse(fs.readFileSync(path.join(dataDir, 'aircraft.json'), 'utf8'));
const ships = JSON.parse(fs.readFileSync(path.join(dataDir, 'ships.json'), 'utf8'));
const weapons = JSON.parse(fs.readFileSync(path.join(dataDir, 'weapons.json'), 'utf8'));
const sensors = JSON.parse(fs.readFileSync(path.join(dataDir, 'sensors.json'), 'utf8'));
const facilities = JSON.parse(fs.readFileSync(path.join(dataDir, 'facilities.json'), 'utf8'));

// ========== Aircraft Wikipedia mappings ==========
// Map designation prefix -> Wikipedia article title
const acWikiMap = {
  'A-10': 'Fairchild_Republic_A-10_Thunderbolt_II',
  'A-37': 'Cessna_A-37_Dragonfly',
  'A-4': 'Douglas_A-4_Skyhawk',
  'A-6': 'Grumman_A-6_Intruder',
  'A-7': 'LTV_A-7_Corsair_II',
  'AC-130': 'Lockheed_AC-130',
  'AH-1': 'Bell_AH-1_Cobra',
  'AH-1Z': 'Bell_AH-1Z_Viper',
  'AH-1W': 'Bell_AH-1_SuperCobra',
  'AH-64': 'Boeing_AH-64_Apache',
  'AH-6': 'MD_Helicopters_MH-6_Little_Bird',
  'AL-1': 'Boeing_YAL-1',
  'AN/TPS-63': 'Tethered_Aerostat_Radar_System',
  'AV-8A': 'Hawker_Siddeley_Harrier',
  'AV-8B': 'McDonnell_Douglas_AV-8B_Harrier_II',
  'AV-8C': 'Hawker_Siddeley_Harrier',
  'B-1': 'Rockwell_B-1_Lancer',
  'B-2': 'Northrop_Grumman_B-2_Spirit',
  'B-52': 'Boeing_B-52_Stratofortress',
  'BQM-74': 'BQM-74_Chukar',
  'C-130': 'Lockheed_C-130_Hercules',
  'C-130J': 'Lockheed_Martin_C-130J_Super_Hercules',
  'C-141': 'Lockheed_C-141_Starlifter',
  'C-17': 'Boeing_C-17_Globemaster_III',
  'C-2': 'Grumman_C-2_Greyhound',
  'C-22': 'Boeing_727',
  'C-32': 'Boeing_C-32',
  'C-40': 'Boeing_C-40_Clipper',
  'C-5': 'Lockheed_C-5_Galaxy',
  'C-9': 'McDonnell_Douglas_C-9',
  'CH-46': 'Boeing_Vertol_CH-46_Sea_Knight',
  'CH-47': 'Boeing_CH-47_Chinook',
  'CH-53D': 'Sikorsky_CH-53_Sea_Stallion',
  'CH-53E': 'Sikorsky_CH-53E_Super_Stallion',
  'CH-53K': 'Sikorsky_CH-53K_King_Stallion',
  'CMV-22': 'Bell_Boeing_V-22_Osprey',
  'CV-22': 'Bell_Boeing_V-22_Osprey',
  'E-2': 'Northrop_Grumman_E-2_Hawkeye',
  'E-3': 'Boeing_E-3_Sentry',
  'E-4': 'Boeing_E-4',
  'E-6': 'Boeing_E-6_Mercury',
  'E-8': 'Northrop_Grumman_E-8_Joint_STARS',
  'EA-18': 'Boeing_EA-18G_Growler',
  'EA-3': 'Douglas_A-3_Skywarrior',
  'EA-6A': 'Grumman_A-6_Intruder',
  'EA-6B': 'Northrop_Grumman_EA-6B_Prowler',
  'EC-130': 'Lockheed_EC-130',
  'EF-111': 'General_Dynamics_EF-111_Raven',
  'EH-60': 'Sikorsky_UH-60_Black_Hawk',
  'EO-5': 'de_Havilland_Canada_Dash_7',
  'EP-3': 'Lockheed_EP-3',
  'ES-3': 'Lockheed_S-3_Viking',
  'F-101': 'McDonnell_F-101_Voodoo',
  'F-105': 'Republic_F-105_Thunderchief',
  'F-106': 'Convair_F-106_Delta_Dart',
  'F-111': 'General_Dynamics_F-111_Aardvark',
  'F-117': 'Lockheed_F-117_Nighthawk',
  'F-14': 'Grumman_F-14_Tomcat',
  'F-15': 'McDonnell_Douglas_F-15_Eagle',
  'F-15E': 'McDonnell_Douglas_F-15E_Strike_Eagle',
  'F-15EX': 'Boeing_F-15EX',
  'F-16': 'General_Dynamics_F-16_Fighting_Falcon',
  'F-22': 'Lockheed_Martin_F-22_Raptor',
  'F-35': 'Lockheed_Martin_F-35_Lightning_II',
  'F-4': 'McDonnell_Douglas_F-4_Phantom_II',
  'F-5': 'Northrop_F-5',
  'F/A-18A': 'McDonnell_Douglas_F/A-18_Hornet',
  'F/A-18C': 'McDonnell_Douglas_F/A-18_Hornet',
  'F/A-18D': 'McDonnell_Douglas_F/A-18_Hornet',
  'F/A-18E': 'Boeing_F/A-18E/F_Super_Hornet',
  'F/A-18F': 'Boeing_F/A-18E/F_Super_Hornet',
  'FB-111': 'General_Dynamics_F-111_Aardvark',
  'FQM-151': 'AeroVironment_RQ-11_Raven',
  'HC-130': 'Lockheed_HC-130',
  'HC-130J-30': 'Lockheed_HC-130',
  'HC-144': 'EADS_CASA_C-295',
  'HH-60': 'Sikorsky_HH-60_Pave_Hawk',
  'HH-65': 'Eurocopter_HH-65_Dolphin',
  'HU-25': 'Dassault_Falcon_20',
  'JLENS': 'JLENS',
  'KA-3': 'Douglas_A-3_Skywarrior',
  'KA-6': 'Grumman_A-6_Intruder',
  'KC-10': 'McDonnell_Douglas_KC-10_Extender',
  'KC-130': 'Lockheed_Martin_KC-130',
  'KC-135': 'Boeing_KC-135_Stratotanker',
  'KC-46': 'Boeing_KC-46_Pegasus',
  'MC-12': 'Beechcraft_King_Air',
  'MC-130': 'Lockheed_MC-130',
  'MH-47': 'Boeing_CH-47_Chinook',
  'MH-53E': 'Sikorsky_CH-53E_Super_Stallion',
  'MH-53J': 'Sikorsky_MH-53_Pave_Low',
  'MH-6': 'MD_Helicopters_MH-6_Little_Bird',
  'MH-60': 'Sikorsky_SH-60_Seahawk',
  'MH-60X': 'Sikorsky_UH-60_Black_Hawk',
  'MH-68': 'MD_Helicopters_MD_900_Explorer',
  'MQ-1B': 'General_Atomics_MQ-1_Predator',
  'MQ-1C': 'General_Atomics_MQ-1C_Gray_Eagle',
  'MQ-25': 'Boeing_MQ-25_Stingray',
  'MQ-4': 'Northrop_Grumman_MQ-4C_Triton',
  'MQ-5': 'Northrop_Grumman_RQ-5_Hunter',
  'MQ-8': 'Northrop_Grumman_MQ-8_Fire_Scout',
  'MQ-9': 'General_Atomics_MQ-9_Reaper',
  'MQM-74': 'BQM-74_Chukar',
  'MV-22': 'Bell_Boeing_V-22_Osprey',
  'O-2': 'Cessna_O-2_Skymaster',
  'O-5': 'Grumman_OV-1_Mohawk',
  'OA-10': 'Fairchild_Republic_A-10_Thunderbolt_II',
  'OH-58': 'Bell_OH-58_Kiowa',
  'OH-6': 'Hughes_OH-6_Cayuse',
  'OV-10': 'North_American_Rockwell_OV-10_Bronco',
  'OV-1': 'Grumman_OV-1_Mohawk',
  'P-3': 'Lockheed_P-3_Orion',
  'P-8': 'Boeing_P-8_Poseidon',
  'RA-5': 'North_American_A-5_Vigilante',
  'RC-12': 'Beechcraft_King_Air',
  'RC-135': 'Boeing_RC-135',
  'RF-4': 'McDonnell_Douglas_F-4_Phantom_II',
  'RF-8': 'Vought_F-8_Crusader',
  'RH-53': 'Sikorsky_CH-53_Sea_Stallion',
  'RQ-170': 'Lockheed_Martin_RQ-170_Sentinel',
  'RQ-180': 'Northrop_Grumman_RQ-180',
  'RQ-1': 'General_Atomics_MQ-1_Predator',
  'RQ-21': 'Boeing_Insitu_RQ-21_Blackjack',
  'RQ-2': 'AAI_RQ-2_Pioneer',
  'RQ-4': 'Northrop_Grumman_RQ-4_Global_Hawk',
  'RQ-5': 'Northrop_Grumman_RQ-5_Hunter',
  'RQ-7': 'AAI_RQ-7_Shadow',
  'RV-1': 'Grumman_OV-1_Mohawk',
  'S-3': 'Lockheed_S-3_Viking',
  'SH-2': 'Kaman_SH-2_Seasprite',
  'SH-3': 'Sikorsky_SH-3_Sea_King',
  'SH-60': 'Sikorsky_SH-60_Seahawk',
  'SR-71': 'Lockheed_SR-71_Blackbird',
  'TF-16': 'General_Dynamics_F-16_Fighting_Falcon',
  'TIF-25': 'Cessna_T-37_Tweet',
  'TR-1': 'Lockheed_U-2',
  'U-2': 'Lockheed_U-2',
  'U-28': 'Pilatus_PC-12',
  'UH-1': 'Bell_UH-1_Iroquois',
  'UH-1Y': 'Bell_UH-1Y_Venom',
  'UH-46': 'Boeing_Vertol_CH-46_Sea_Knight',
  'UH-60': 'Sikorsky_UH-60_Black_Hawk',
  'UH-72': 'Eurocopter_UH-72_Lakota',
  'VC-25': 'Boeing_VC-25',
  'V-22': 'Bell_Boeing_V-22_Osprey',
};

// ========== Ship Wikipedia mappings ==========
const shipWikiMap = {
  '95300': 'Cape-class_mine_countermeasures_ship',
  '95312': 'Cape-class_mine_countermeasures_ship',
  '95321': 'Cape-class_mine_countermeasures_ship',
  'AE 21': 'Suribachi-class_ammunition_ship',
  'AE 23': 'Nitro-class_ammunition_ship',
  'AE 26': 'Kilauea-class_ammunition_ship',
  'AE 27': 'Kilauea-class_ammunition_ship',
  'AFS 1': 'Mars-class_combat_stores_ship',
  'AFSB': 'Afloat_Forward_Staging_Base',
  'AGF 11': 'USS_Coronado_(AGF-11)',
  'AGF 3': 'USS_La_Salle_(AGF-3)',
  'AO 105': 'Mispillion-class_oiler',
  'AO 177': 'Cimarron-class_oiler_(1981)',
  'AO 51': 'Ashtabula-class_oiler',
  'AOE 1': 'Sacramento-class_fast_combat_support_ship',
  'AOE 6': 'Supply-class_fast_combat_support_ship',
  'AOE 8': 'Supply-class_fast_combat_support_ship',
  'AOR 1': 'Wichita-class_replenishment_oiler',
  'AS 36': 'Spear-class_submarine_tender',
  'BB 61': 'Iowa-class_battleship',
  'BB 62': 'Iowa-class_battleship',
  'BB 63': 'Iowa-class_battleship',
  'BB 64': 'Iowa-class_battleship',
  'CG 10': 'Albany-class_cruiser',
  'CG 16': 'Leahy-class_cruiser',
  'CG 26': 'Belknap-class_cruiser',
  'CG 27': 'Belknap-class_cruiser',
  'CG 47': 'Ticonderoga-class_cruiser',
  'CG 49': 'Ticonderoga-class_cruiser',
  'CG 52': 'Ticonderoga-class_cruiser',
  'CG 54': 'Ticonderoga-class_cruiser',
  'CG 56': 'Ticonderoga-class_cruiser',
  'CG 59': 'Ticonderoga-class_cruiser',
  'CG 68': 'Ticonderoga-class_cruiser',
  'CG 70': 'Ticonderoga-class_cruiser',
  'CGN 25': 'USS_Bainbridge_(CGN-25)',
  'CGN 35': 'USS_Truxtun_(CGN-35)',
  'CGN 36': 'California-class_cruiser',
  'CGN 38': 'Virginia-class_cruiser',
  'CGN 9': 'USS_Long_Beach_(CGN-9)',
  'CV 41': 'USS_Midway_(CV-41)',
  'CV 43': 'USS_Coral_Sea_(CV-43)',
  'CV 59': 'Forrestal-class_aircraft_carrier',
  'CV 60': 'Forrestal-class_aircraft_carrier',
  'CV 61': 'Forrestal-class_aircraft_carrier',
  'CV 62': 'Forrestal-class_aircraft_carrier',
  'CV 63': 'Kitty_Hawk-class_aircraft_carrier',
  'CV 64': 'Kitty_Hawk-class_aircraft_carrier',
  'CV 66': 'USS_America_(CV-66)',
  'CV 67': 'USS_John_F._Kennedy_(CV-67)',
  'CVN 65': 'USS_Enterprise_(CVN-65)',
  'CVN 68': 'Nimitz-class_aircraft_carrier',
  'CVN 69': 'Nimitz-class_aircraft_carrier',
  'CVN 70': 'Nimitz-class_aircraft_carrier',
  'CVN 71': 'Nimitz-class_aircraft_carrier',
  'CVN 72': 'Nimitz-class_aircraft_carrier',
  'CVN 73': 'Nimitz-class_aircraft_carrier',
  'CVN 74': 'Nimitz-class_aircraft_carrier',
  'CVN 75': 'Nimitz-class_aircraft_carrier',
  'CVN 76': 'Nimitz-class_aircraft_carrier',
  'CVN 77': 'Nimitz-class_aircraft_carrier',
  'CVN 78': 'Gerald_R._Ford-class_aircraft_carrier',
  'CVN 79': 'Gerald_R._Ford-class_aircraft_carrier',
  'CVN 80': 'Gerald_R._Ford-class_aircraft_carrier',
  'DD 931': 'Forrest_Sherman-class_destroyer',
  'DD 963': 'Spruance-class_destroyer',
  'DDG 1000': 'Zumwalt-class_destroyer',
  'DDG 103': 'Arleigh_Burke-class_destroyer',
  'DDG 113': 'Arleigh_Burke-class_destroyer',
  'DDG 116': 'Arleigh_Burke-class_destroyer',
  'DDG 124': 'Arleigh_Burke-class_destroyer',
  'DDG 19': 'Charles_F._Adams-class_destroyer',
  'DDG 2': 'Charles_F._Adams-class_destroyer',
  'DDG 31': 'Decatur-class_destroyer',
  'DDG 37': 'Farragut-class_destroyer_(1958)',
  'DDG 42': 'Farragut-class_destroyer_(1958)',
  'DDG 51': 'Arleigh_Burke-class_destroyer',
  'DDG 72': 'Arleigh_Burke-class_destroyer',
  'DDG 79': 'Arleigh_Burke-class_destroyer',
  'DDG 81': 'Arleigh_Burke-class_destroyer',
  'DDG 85': 'Arleigh_Burke-class_destroyer',
  'DDG 91': 'Arleigh_Burke-class_destroyer',
  'DDG 96': 'Arleigh_Burke-class_destroyer',
  'DDG 993': 'Kidd-class_destroyer',
  'EPF 1': 'Spearhead-class_expeditionary_fast_transport',
  'ESB 1': 'Expeditionary_mobile_base',
  'ESD 1': 'Expeditionary_mobile_base',
  'FF 1040': 'Garcia-class_frigate',
  'FF 1052': 'Knox-class_frigate',
  'FFG 1': 'Brooke-class_frigate',
  'FFG 36': 'Oliver_Hazard_Perry-class_frigate',
  'FFG 7': 'Oliver_Hazard_Perry-class_frigate',
  'FFG 62': 'Constellation-class_frigate',
  'Fleet': 'Unmanned_surface_vehicle',
  'HSV 2': 'HSV-2_Swift',
  'LCAC': 'Landing_Craft_Air_Cushion',
  'LCC 19': 'Blue_Ridge-class_command_ship',
  'LCM': 'Landing_craft_mechanized',
  'LCP': 'Landing_Craft,_Personnel',
  'LCS 1': 'Freedom-class_littoral_combat_ship',
  'LCS 17': 'Independence-class_littoral_combat_ship',
  'LCS 2': 'Independence-class_littoral_combat_ship',
  'LCU': 'Landing_Craft_Utility',
  'LCVP': 'LCVP_(United_States)',
  'LHA 1': 'Tarawa-class_amphibious_assault_ship',
  'LHA 6': 'America-class_amphibious_assault_ship',
  'LHD 1': 'Wasp-class_amphibious_assault_ship',
  'LHD 2': 'Wasp-class_amphibious_assault_ship',
  'LHD 8': 'Wasp-class_amphibious_assault_ship',
  'LKA 113': 'Charleston-class_amphibious_cargo_ship',
  'LPD 1': 'Raleigh-class_amphibious_transport_dock',
  'LPD 17': 'San_Antonio-class_amphibious_transport_dock',
  'LPD 4': 'Austin-class_amphibious_transport_dock',
  'LPH 2': 'Iwo_Jima-class_helicopter_carrier',
  'LSD 28': 'Thomaston-class_dock_landing_ship',
  'LSD 36': 'Anchorage-class_dock_landing_ship',
  'LSD 41': 'Whidbey_Island-class_dock_landing_ship',
  'LSD 49': 'Harpers_Ferry-class_dock_landing_ship',
  'LST 1179': 'Newport-class_tank_landing_ship',
  'LST 1184': 'Newport-class_tank_landing_ship',
  'LSV 1': 'Frank_S._Besson-class_logistics_support_vessel',
  'MCM 1': 'Avenger-class_mine_countermeasures_ship',
  'MCS 12': 'USS_Inchon_(MCS-12)',
  'MHC 51': 'Osprey-class_coastal_minehunter',
  'MSO 422': 'Aggressive-class_minesweeper',
  'MSO 508': 'Aggressive-class_minesweeper',
  'MSV': 'Mine_countermeasures_vessel',
  'NSWTU': 'Naval_Special_Warfare_Command',
  'PC 1': 'Cyclone-class_patrol_ship',
  'PGM 84': 'Asheville-class_gunboat',
  'PHM 1': 'Pegasus-class_hydrofoil',
  'RB-M': 'Rigid-hulled_inflatable_boat',
  'SBX 1': 'Sea-based_X-band_Radar',
  'Sea Hunter': 'Sea_Hunter',
  'T-AE': 'Kilauea-class_ammunition_ship',
  'T-AFS': 'Mars-class_combat_stores_ship',
  'T-AGM': 'Missile_Range_Instrumentation_Ship',
  'T-AGOS': 'Stalwart-class_ocean_surveillance_ship',
  'T-AH': 'Mercy-class_hospital_ship',
  'T-AK': 'Military_Sealift_Command',
  'T-AKE': 'Lewis_and_Clark-class_dry_cargo_ship',
  'T-AKR': 'Military_Sealift_Command',
  'T-AO': 'Henry_J._Kaiser-class_oiler',
  'T-AOE': 'Supply-class_fast_combat_support_ship',
  'T-AOT': 'Military_Sealift_Command',
  'T-AVB': 'Aviation_Logistics_Support_Ship',
  'US 11m': 'Rigid-hulled_inflatable_boat',
  'US 7m': 'Rigid-hulled_inflatable_boat',
  'US CCM': 'Combatant_Craft_Medium',
  'US Mk3': 'Mark_V_Special_Operations_Craft',
  'US Mk5': 'Mark_V_Special_Operations_Craft',
  'US Mk6': 'Mark_VI_patrol_boat',
  'US SOC-R': 'Special_Operations_Craft_%E2%80%93_Riverine',
  'US SWCL': 'Patrol_boat',
  'WHEC': 'Hamilton-class_cutter',
  'WMEC 39': 'USCGC_Alex_Haley_(WMEC-39)',
  'WMEC 615': 'Reliance-class_cutter',
  'WMEC 901': 'Bear-class_cutter',
  'WMSL': 'Legend-class_cutter',
  'WPB 1301': 'Island-class_patrol_boat',
  'WPB 1317': 'Island-class_patrol_boat',
  'WPB 1338': 'Island-class_patrol_boat',
  'WPB 82301': 'Point-class_cutter',
  'WPB 87301': 'Marine_Protector-class_coastal_patrol_boat',
  'WPC 1101': 'Sentinel-class_cutter',
  // Submarines
  'AN/SLQ-48': 'AN/SLQ-48_Mine_Neutralization_Vehicle',
  'AN/WLD-1': 'AN/WLD-1_Remote_Minehunting_System',
  'Echo Voyager': 'Echo_Voyager',
  'Knifefish': 'Knifefish_(unmanned_vehicle)',
  'Mk18 Mod': 'Bluefin-21',
  'Seafox': 'Seafox_(mine_disposal_system)',
  'SEAL ASDS': 'Advanced_SEAL_Delivery_System',
  'SEAL SDV': 'SEAL_Delivery_Vehicle',
  'SS 580': 'Barbel-class_submarine',
  'SSBN 616': 'Lafayette-class_submarine',
  'SSBN 627': 'James_Madison-class_submarine',
  'SSBN 640': 'Benjamin_Franklin-class_submarine',
  'SSBN 726': 'Ohio-class_submarine',
  'SSBN 734': 'Ohio-class_submarine',
  'SSGN 726': 'Ohio-class_submarine',
  'SSN 21': 'Seawolf-class_submarine',
  'SSN 23': 'USS_Jimmy_Carter_(SSN-23)',
  'SSN 585': 'Skipjack-class_submarine',
  'SSN 594': 'Permit-class_submarine',
  'SSN 637': 'Sturgeon-class_submarine',
  'SSN 642': 'USS_Kamehameha_(SSN-642)',
  'SSN 671': 'USS_Narwhal_(SSN-671)',
  'SSN 678': 'Sturgeon-class_submarine',
  'SSN 685': 'USS_Glenard_P._Lipscomb_(SSN-685)',
  'SSN 688': 'Los_Angeles-class_submarine',
  'SSN 700': 'Los_Angeles-class_submarine',
  'SSN 716': 'Los_Angeles-class_submarine',
  'SSN 719': 'Los_Angeles-class_submarine',
  'SSN 751': 'Los_Angeles-class_submarine',
  'SSN 771': 'Los_Angeles-class_submarine',
  'SSN 774': 'Virginia-class_submarine',
  'SSN 778': 'Virginia-class_submarine',
  'SSN 784': 'Virginia-class_submarine',
  'SSN 792': 'Virginia-class_submarine',
  'SSN 802': 'Virginia-class_submarine',
};

// ========== Weapon Wikipedia mappings ==========
const wpnWikiMap = {
  'AGM-114': 'AGM-114_Hellfire',
  'AGM-119': 'AGM-119_Penguin',
  'AGM-12': 'AGM-12_Bullpup',
  'AGM-123': 'AGM-123_Skipper_II',
  'AGM-129': 'AGM-129_ACM',
  'AGM-142': 'AGM-142_Have_Nap',
  'AGM-154': 'Joint_Standoff_Weapon',
  'AGM-158': 'AGM-158_JASSM',
  'AGM-45': 'AGM-45_Shrike',
  'AGM-62': 'AGM-62_Walleye',
  'AGM-65': 'AGM-65_Maverick',
  'AGM-69': 'AGM-69_SRAM',
  'AGM-78': 'AGM-78_Standard_ARM',
  'AGM-84': 'AGM-84_Harpoon',
  'AGM-86': 'AGM-86_ALCM',
  'AGM-88': 'AGM-88_HARM',
  'AIM-120': 'AIM-120_AMRAAM',
  'AIM-132': 'ASRAAM',
  'AIM-4': 'AIM-4_Falcon',
  'AIM-54': 'AIM-54_Phoenix',
  'AIM-7': 'AIM-7_Sparrow',
  'AIM-9': 'AIM-9_Sidewinder',
  'AIM-92': 'FIM-92_Stinger',
  'BGM-109': 'Tomahawk_(missile)',
  'CBU-100': 'CBU-87_Combined_Effects_Munition',
  'CBU-103': 'CBU-87_Combined_Effects_Munition',
  'CBU-105': 'CBU-97_Sensor_Fuzed_Weapon',
  'CBU-52': 'Cluster_munition',
  'CBU-55': 'BLU-73/B',
  'CBU-58': 'Cluster_munition',
  'CBU-59': 'Cluster_munition',
  'CBU-71': 'Cluster_munition',
  'CBU-72': 'BLU-73/B',
  'CBU-78': 'Cluster_munition',
  'CBU-87': 'CBU-87_Combined_Effects_Munition',
  'CBU-89': 'CBU-89_Gator',
  'CBU-97': 'CBU-97_Sensor_Fuzed_Weapon',
  'FIM-43': 'FIM-43_Redeye',
  'FIM-92': 'FIM-92_Stinger',
  'GBI': 'Ground-Based_Interceptor',
  'GBU-10': 'GBU-10_Paveway_II',
  'GBU-12': 'GBU-12_Paveway_II',
  'GBU-15': 'GBU-15',
  'GBU-16': 'Paveway_II',
  'GBU-24': 'GBU-24_Paveway_III',
  'GBU-27': 'GBU-27_Paveway_III',
  'GBU-28': 'GBU-28',
  'GBU-31': 'Joint_Direct_Attack_Munition',
  'GBU-32': 'Joint_Direct_Attack_Munition',
  'GBU-38': 'Joint_Direct_Attack_Munition',
  'GBU-39': 'Small_Diameter_Bomb',
  'GBU-53': 'GBU-53/B_StormBreaker',
  'GBU-54': 'Joint_Direct_Attack_Munition',
  'GBU-56': 'Joint_Direct_Attack_Munition',
  'GBU-57': 'Massive_Ordnance_Penetrator',
  'LRASM': 'Long_Range_Anti-Ship_Missile',
  'MGM-140': 'MGM-140_ATACMS',
  'MGM-168': 'MGM-140_ATACMS',
  'MGM-52': 'MGM-52_Lance',
  'MIM-104': 'MIM-104_Patriot',
  'MIM-23': 'MIM-23_Hawk',
  'Mk36': 'Quickstrike_mine',
  'Mk46': 'Mark_46_torpedo',
  'Mk48': 'Mark_48_torpedo',
  'Mk50': 'Mark_50_torpedo',
  'Mk54': 'Mark_54_torpedo',
  'Mk56': 'Quickstrike_mine',
  'Mk60': 'Mark_60_CAPTOR',
  'Mk62': 'Quickstrike_mine',
  'Mk63': 'Quickstrike_mine',
  'Mk64': 'Quickstrike_mine',
  'Mk65': 'Quickstrike_mine',
  'Mk67': 'Quickstrike_mine',
  'Mk82': 'Mark_82_bomb',
  'Mk83': 'Mark_83_bomb',
  'Mk84': 'Mark_84_bomb',
  'NSM': 'Naval_Strike_Missile',
  'RGM-84': 'AGM-84_Harpoon',
  'RIM-116': 'RIM-116_Rolling_Airframe_Missile',
  'RIM-156': 'RIM-156_Standard_Missile_2',
  'RIM-161': 'RIM-161_Standard_Missile_3',
  'RIM-162': 'RIM-162_ESSM',
  'RIM-174': 'RIM-174_Standard_ERAM',
  'RIM-2': 'RIM-2_Terrier',
  'RIM-24': 'RIM-24_Tartar',
  'RIM-66': 'Standard_Missile',
  'RIM-67': 'Standard_Missile',
  'RIM-7': 'RIM-7_Sea_Sparrow',
  'RIM-8': 'RIM-8_Talos',
  'RUR-5': 'RUR-5_ASROC',
  'SLAM-ER': 'Standoff_Land_Attack_Missile',
  'THAAD': 'Terminal_High_Altitude_Area_Defense',
  'UGM-133': 'Trident_(missile)',
  'UGM-84': 'UGM-84_Sub-Harpoon',
  'UGM-109': 'Tomahawk_(missile)',
  'UGM-96': 'Trident_(missile)',
  'BGM-71': 'BGM-71_TOW',
  'MGM-31': 'MGM-31_Pershing',
  'MGM-164': 'MGM-140_ATACMS',
  'MIM-72': 'MIM-72_Chaparral',
  'MIM-120': 'HUMRAAM',
  'GBU-43': 'GBU-43/B_MOAB',
  'GBU-8': 'GBU-8_HOBOS',
  'GBU-22': 'Paveway_III',
  'GBU-36': 'Joint_Direct_Attack_Munition',
  'GBU-37': 'Joint_Direct_Attack_Munition',
  'GBU-44': 'GBU-44/B_Viper_Strike',
  'GBU-49': 'Paveway_II',
  'GBU-58': 'Paveway_II',
  'GBU-59': 'Paveway_II',
  'AIM-23': 'MIM-23_Hawk',
  'CBU-104': 'Wind_Corrected_Munitions_Dispenser',
  '127mm/54': 'Mark_45_5-inch_gun',
  '127mm/62': 'Mark_45_5-inch_gun',
  '20mm/85': 'Phalanx_CIWS',
  '25mm/87': 'Mk_38_25_mm_machine_gun_system',
  '76mm/62': 'OTO_Melara_76_mm',
  '57mm/70': 'Bofors_57_mm_gun',
  'Standard': 'Standard_Missile',
  'Griffin': 'Griffin_(missile)',
  'Mk81': 'Mark_81_bomb',
};

// ========== Sensor Wikipedia mappings ==========
// Sensors mostly use their designation directly as wiki title
const snWikiMap = {
  'AN/AAQ-13': 'LANTIRN',
  'AN/AAQ-14': 'LANTIRN',
  'AN/AAQ-28': 'LITENING_pod',
  'AN/AAQ-33': 'Sniper_Advanced_Targeting_Pod',
  'AN/AAQ-37': 'AN/AAQ-37',
  'AN/AAQ-40': 'AN/AAQ-40',
  'AN/AAR-47': 'AN/AAR-47',
  'AN/AAR-49': 'LANTIRN',
  'AN/AAR-54': 'AN/AAR-54',
  'AN/AAR-57': 'AN/AAR-57',
  'AN/ALQ-100': 'AN/ALQ-100',
  'AN/ALQ-119': 'AN/ALQ-119',
  'AN/ALQ-126': 'AN/ALQ-126',
  'AN/ALQ-131': 'AN/ALQ-131',
  'AN/ALQ-135': 'AN/ALQ-135',
  'AN/ALQ-144': 'AN/ALQ-144',
  'AN/ALQ-165': 'AN/ALQ-165',
  'AN/ALQ-184': 'AN/ALQ-184',
  'AN/ALQ-99': 'AN/ALQ-99',
  'AN/ALR-56': 'AN/ALR-56',
  'AN/ALR-67': 'AN/ALR-67',
  'AN/ALR-69': 'AN/ALR-69',
  'AN/ALR-94': 'Lockheed_Martin_F-22_Raptor',
  'AN/APG-63': 'AN/APG-63',
  'AN/APG-65': 'AN/APG-65',
  'AN/APG-66': 'AN/APG-66',
  'AN/APG-68': 'AN/APG-68',
  'AN/APG-70': 'AN/APG-70',
  'AN/APG-71': 'AN/APG-71',
  'AN/APG-73': 'AN/APG-73',
  'AN/APG-77': 'AN/APG-77',
  'AN/APG-78': 'AN/APG-78',
  'AN/APG-79': 'AN/APG-79',
  'AN/APG-80': 'AN/APG-80',
  'AN/APG-81': 'AN/APG-81',
  'AN/APG-83': 'AN/APG-83',
  'AN/APN-194': 'Radar_altimeter',
  'AN/APN-234': 'Radar_altimeter',
  'AN/APN-59': 'Radar_altimeter',
  'AN/APQ-120': 'AN/APQ-120',
  'AN/APQ-148': 'Grumman_A-6_Intruder',
  'AN/APQ-156': 'Grumman_A-6_Intruder',
  'AN/APS-115': 'Lockheed_P-3_Orion',
  'AN/APS-116': 'Lockheed_P-3_Orion',
  'AN/APS-124': 'Sikorsky_SH-60_Seahawk',
  'AN/APS-125': 'Northrop_Grumman_E-2_Hawkeye',
  'AN/APS-137': 'Boeing_P-8_Poseidon',
  'AN/APS-138': 'Northrop_Grumman_E-2_Hawkeye',
  'AN/APS-139': 'Northrop_Grumman_E-2_Hawkeye',
  'AN/APS-145': 'Northrop_Grumman_E-2_Hawkeye',
  'AN/APS-149': 'Boeing_P-8_Poseidon',
  'AN/APS-153': 'Sikorsky_SH-60_Seahawk',
  'AN/APS-154': 'Boeing_P-8_Poseidon',
  'AN/APY-1': 'Boeing_E-3_Sentry',
  'AN/APY-2': 'Boeing_E-3_Sentry',
  'AN/APY-3': 'Northrop_Grumman_E-8_Joint_STARS',
  'AN/APY-9': 'AN/APY-9',
  'AN/APY-10': 'Boeing_P-8_Poseidon',
  'AN/ASQ-239': 'Lockheed_Martin_F-35_Lightning_II',
  'AN/AWG-9': 'AN/AWG-9',
  'AN/BQQ-10': 'AN/BQQ-10',
  'AN/BQQ-5': 'AN/BQQ-5',
  'AN/BQQ-6': 'AN/BQQ-5',
  'AN/BSY-1': 'AN/BSY-1',
  'AN/SLQ-25': 'AN/SLQ-25_Nixie',
  'AN/SLQ-32': 'AN/SLQ-32',
  'AN/SPG-51': 'AN/SPG-51',
  'AN/SPG-55': 'AN/SPG-55',
  'AN/SPG-60': 'Mark_86_gunfire_control_system',
  'AN/SPG-62': 'AN/SPG-62',
  'AN/SPS-10': 'AN/SPS-10',
  'AN/SPS-40': 'AN/SPS-40',
  'AN/SPS-48': 'AN/SPS-48',
  'AN/SPS-49': 'AN/SPS-49',
  'AN/SPS-52': 'AN/SPS-52',
  'AN/SPS-55': 'AN/SPS-55',
  'AN/SPS-64': 'AN/SPS-64',
  'AN/SPS-67': 'AN/SPS-67',
  'AN/SPY-1': 'AN/SPY-1',
  'AN/SPY-6': 'AN/SPY-6',
  'AN/SQQ-32': 'Avenger-class_mine_countermeasures_ship',
  'AN/SQQ-89': 'AN/SQQ-89',
  'AN/SQR-18': 'Surveillance_Towed_Array_Sensor_System',
  'AN/SQR-19': 'Surveillance_Towed_Array_Sensor_System',
  'AN/SQS-26': 'AN/SQS-26',
  'AN/SQS-53': 'AN/SQS-53',
  'AN/SQS-56': 'AN/SQS-56',
  'AN/TB-16': 'Surveillance_Towed_Array_Sensor_System',
  'AN/TB-23': 'Surveillance_Towed_Array_Sensor_System',
  'AN/TB-29': 'Surveillance_Towed_Array_Sensor_System',
  'AN/TPY-2': 'AN/TPY-2',
  'AN/TPS-59': 'AN/TPS-59',
  'AN/TPS-80': 'AN/TPS-80',
  'TADS/PNVS': 'TADS/PNVS',
};

// ========== Facility Wikipedia mappings ==========
const facWikiMap = {
  'AAA': 'M163_VADS',
  'Armored Plt (M1 ': 'M1_Abrams',
  'Armored Plt (M1128': 'M1128_Mobile_Gun_System',
  'Armored Plt (M1A1': 'M1_Abrams',
  'Armored Plt (M1A2': 'M1_Abrams',
  'Armored Plt (M60': 'M60_tank',
  'Arty Bty (105mm/22': 'M101_howitzer',
  'Arty Bty (105mm/32': 'M102_howitzer',
  'Arty Bty (155mm/23 M109A3': 'M109_howitzer',
  'Arty Bty (155mm/39 M109A5': 'M109_howitzer',
  'Arty Bty (155mm/39 M109A6': 'M109_howitzer',
  'Arty Bty (155mm/39 M109A7': 'M109_howitzer',
  'Arty Bty (155mm/39 M198': 'M198_howitzer',
  'Arty Bty (155mm/39 M777': 'M777_howitzer',
  'Arty Bty (203mm': 'M110_howitzer',
  'Arty Plt (HIMARS)': 'HIMARS',
  'Arty Plt (MLRS)': 'M270_Multiple_Launch_Rocket_System',
  'Bottom Fixed Array': 'SOSUS',
  'HF/DF': 'AN/FLR-9',
  'Inf Plt': 'United_States_Army_Rangers',
  'Inf Sec': 'United_States_special_operations_forces',
  'Mech Inf Plt (LAV': 'LAV-25',
  'Mech Inf Plt (M1126': 'Stryker',
  'Mech Inf Plt (M113': 'M113_armored_personnel_carrier',
  'Mech Inf Plt (M2': 'M2_Bradley',
  'Mech Inf Plt (M3': 'M3_Bradley',
  'Mech Inf Plt (XM1296': 'Stryker',
  'Mech Inf Sec (AAV': 'Assault_Amphibious_Vehicle',
  'Radar (AN/FPS-108': 'AN/FPS-108_Cobra_Dane',
  'Radar (AN/FPS-115': 'PAVE_PAWS',
  'Radar (AN/FPS-117': 'AN/FPS-117',
  'Radar (AN/FPS-118': 'AN/FPS-118_Over-the-Horizon-Backscatter',
  'Radar (AN/FPS-120': 'Ballistic_Missile_Early_Warning_System',
  'Radar (AN/FPS-123': 'Ballistic_Missile_Early_Warning_System',
  'Radar (AN/FPS-124': 'North_Warning_System',
  'Radar (AN/FPS-126': 'Ballistic_Missile_Early_Warning_System',
  'Radar (AN/FPS-130': 'Space_Surveillance_Telescope',
  'Radar (AN/FPS-49': 'Ballistic_Missile_Early_Warning_System',
  'Radar (AN/FPS-50': 'Ballistic_Missile_Early_Warning_System',
  'Radar (AN/FPS-66': 'Ground-controlled_approach',
  'Radar (AN/FPS-85': 'AN/FPS-85',
  'Radar (AN/FPS-92': 'Ballistic_Missile_Early_Warning_System',
  'Radar (AN/FPS-93': 'Safeguard_Program',
  'Radar (AN/MPQ-49': 'AN/MPQ-49_Forward_Area_Alerting_Radar',
  'Radar (AN/MPQ-64': 'AN/MPQ-64_Sentinel',
  'Radar (AN/TPQ-36': 'AN/TPQ-36_Firefinder_radar',
  'Radar (AN/TPQ-37': 'AN/TPQ-37_Firefinder_radar',
  'Radar (AN/TPS-43': 'AN/TPS-43',
  'Radar (AN/TPS-59': 'AN/TPS-59',
  'Radar (AN/TPS-63': 'Tethered_Aerostat_Radar_System',
  'Radar (AN/TPS-71': 'Relocatable_Over-the-Horizon_Radar',
  'Radar (AN/TPS-73': 'Marine_Air_Traffic_Control_and_Landing_System',
  'Radar (AN/TPS-75': 'AN/TPS-75',
  'Radar (AN/TPS-77': 'AN/TPS-77',
  'Radar (AN/TPS-80': 'AN/TPS-80',
  'Radar (AN/TPY-2)': 'AN/TPY-2',
  'Radar (AN/UPS-3': 'Tethered_Aerostat_Radar_System',
  'Radar (ARSR-4)': 'Airport_surveillance_radar',
  'Radar (ASR-9': 'Airport_surveillance_radar',
  'Radar (JLENS': 'JLENS',
  'SAM Bty (I-HAWK': 'MIM-23_Hawk',
  'SAM Bty (Nike': 'Nike_Hercules',
  'SAM Bty (Patriot': 'MIM-104_Patriot',
  'SAM Bty (THAAD': 'Terminal_High_Altitude_Area_Defense',
  'SAM Plt (HUMRAAM': 'HUMRAAM',
  'SAM Plt (I-HAWK': 'MIM-23_Hawk',
  'SAM Plt (NASAMS': 'NASAMS',
  'SAM Plt/2 (Chaparral': 'MIM-72_Chaparral',
  'SAM Plt/2 (NASAMS': 'NASAMS',
  'SAM Sec (Avenger': 'AN/TWQ-1_Avenger',
  'SAM Sec (Bradley': 'M6_Linebacker',
  'SAM Sec (LAV-AD': 'LAV-AD',
  'SAM Sec (Redeye': 'FIM-43_Redeye',
  'SAM Sec (Stinger': 'FIM-92_Stinger',
  'SAM Section (AEGIS': 'Aegis_Ashore',
  'SAM Section (GBI': 'Ground-Based_Interceptor',
  'Sensor': 'Electro-optical_targeting_system',
  'SSM Flt (BGM-109G': 'Ground_Launched_Cruise_Missile',
  'SSM Plt (FGM-148': 'FGM-148_Javelin',
  'SSM Plt (MGM-52': 'MGM-52_Lance',
  'SSM Plt (Pershing IA': 'MGM-31_Pershing',
  'SSM Plt (Pershing II': 'Pershing_II',
  'SSM Silo (Minuteman II': 'LGM-30_Minuteman',
  'SSM Silo (Minuteman III': 'LGM-30_Minuteman',
  'SSM Silo (Peacekeeper': 'LGM-118_Peacekeeper',
  'SSM Silo (Titan': 'LGM-25C_Titan_II',
  'Support Coy': 'BQM-74_Chukar',
  'Mech Inf Plt (United': 'United_States_Army',
};

// ========== Build images.json ==========
const images = { aircraft: {}, ships: {}, weapons: {}, sensors: {}, facilities: {} };

// Aircraft
for (const ac of aircraft) {
  const desig = ac.name.match(/^([A-Z][\w\/-]+\d[A-Z]*)/)?.[1];
  if (!desig) continue;
  // Try exact match first, then progressively shorter prefixes
  let wiki = acWikiMap[desig];
  if (!wiki) {
    // Try without letter suffix: F-14A -> F-14
    const base = desig.replace(/[A-Z]+$/, '');
    wiki = acWikiMap[base];
  }
  if (!wiki) {
    // Try just the type: F-14A -> F-14
    const typeOnly = desig.match(/^([A-Z][\w\/-]+-?\d+)/)?.[1];
    wiki = acWikiMap[typeOnly];
  }
  if (wiki) images.aircraft[ac.id] = wiki;
}

// Ships (includes subs)
for (const s of ships) {
  let wiki = null;
  // Try matching ship name prefixes
  const name = s.name;
  for (const [prefix, title] of Object.entries(shipWikiMap)) {
    if (name.startsWith(prefix)) { wiki = title; break; }
  }
  if (wiki) images.ships[s.id] = wiki;
}

// Weapons
for (const w of weapons) {
  let wiki = null;
  const name = w.name;
  for (const [prefix, title] of Object.entries(wpnWikiMap)) {
    if (name.startsWith(prefix)) { wiki = title; break; }
  }
  if (wiki) images.weapons[w.id] = wiki;
}

// Sensors
for (const s of sensors) {
  let wiki = null;
  const name = s.name;
  // Try exact name match first
  for (const [prefix, title] of Object.entries(snWikiMap)) {
    if (name.startsWith(prefix)) { wiki = title; break; }
  }
  // Fallback: use AN/ designation as wiki title
  if (!wiki) {
    const m = name.match(/^(AN\/[A-Z]+-\d+)/);
    if (m) wiki = m[1];
  }
  if (wiki) images.sensors[s.id] = wiki;
}

// Facilities
for (const f of facilities) {
  let wiki = null;
  const name = f.name;
  for (const [prefix, title] of Object.entries(facWikiMap)) {
    if (name.startsWith(prefix)) { wiki = title; break; }
  }
  if (wiki) images.facilities[f.id] = wiki;
}

// Write
const outPath = path.join(dataDir, 'images.json');
fs.writeFileSync(outPath, JSON.stringify(images, null, 2));

const counts = {
  aircraft: Object.keys(images.aircraft).length,
  ships: Object.keys(images.ships).length,
  weapons: Object.keys(images.weapons).length,
  sensors: Object.keys(images.sensors).length,
  facilities: Object.keys(images.facilities).length,
};
console.log('Image mappings generated:');
console.log(`  Aircraft: ${counts.aircraft}/${aircraft.length}`);
console.log(`  Ships: ${counts.ships}/${ships.length}`);
console.log(`  Weapons: ${counts.weapons}/${weapons.length}`);
console.log(`  Sensors: ${counts.sensors}/${sensors.length}`);
console.log(`  Facilities: ${counts.facilities}/${facilities.length}`);
console.log(`  Total: ${Object.values(counts).reduce((a,b)=>a+b, 0)}`);
